### ISSUE TITLE
can't install due to failing test at t/form.t:86 

### ISSUE THREAD

**Issue by kfwebmaster** [libwww-perl/HTML-Form#52] opened 2024-10-16 11:39 UTC
my machine:
perl 5.40.0 (via plenv)
macOS Sequioa 15.0.1 on a MacBook Pro M2 

test output:
```
$ make test                 
PERL_DL_NONLAZY=1 "/Users/levi/.plenv/versions/5.40.0/bin/perl5.40.0" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-report-prereqs.t .. # 
# Versions for all modules listed in MYMETA.json (including optional ones):
# 
# === Configure Requires ===
# 
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 7.70
# 
# === Configure Suggests ===
# 
#     Module      Want Have
#     -------- ------- ----
#     JSON::PP 2.27300 4.16
# 
# === Build Requires ===
# 
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 7.70
# 
# === Test Requires ===
# 
#     Module              Want     Have
#     ------------------- ---- --------
#     ExtUtils::MakeMaker  any     7.70
#     File::Spec           any     3.90
#     HTTP::Response       any     7.00
#     Test::More          0.96 1.302199
#     Test::Warnings       any    0.033
#     warnings             any     1.70
# 
# === Test Recommends ===
# 
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.150010
# 
# === Runtime Requires ===
# 
#     Module                Want     Have
#     --------------------- ---- --------
#     Carp                   any     1.54
#     Encode                   2     3.21
#     HTML::TokeParser       any     3.83
#     HTTP::Request            6     7.00
#     HTTP::Request::Common 6.03     7.00
#     Test::More            0.96 1.302199
#     URI                   1.10     5.30
#     parent                 any    0.241
#     strict                 any     1.13
# 
t/00-report-prereqs.t .. ok   
t/autocomplete.t ....... ok   
t/file_upload.t ........ ok    
t/find_input.t ......... ok   
t/form-label.t ......... ok   
t/form-maxlength.t ..... ok     
t/form-multi-select.t .. ok   
t/form-param.t ......... ok    
t/form-parse.t ......... ok   
t/form-selector.t ...... ok     
t/form-unicode.t ....... ok     
t/form.t ............... 1/? 
#   Failed test at t/form.t line 86.
#          got: 'POST http://localhost/
# Content-Length: 80
# Content-Type: application/x-www-form-urlencoded
# 
# i.x=1&i.y=1&c=on&r=b&t=&p=&tel=&date=&h=xyzzy&f=&x=&a=%0Aabc%0A+++&s=bar&m=a&m=b
# '
#     expected: 'POST http://localhost/
# Content-Length: 86
# Content-Type: application/x-www-form-urlencoded
# 
# i.x=1&i.y=1&c=on&r=b&t=&p=&tel=&date=&h=xyzzy&f=&x=&a=%0D%0Aabc%0D%0A+++&s=bar&m=a&m=b
# '
# Looks like you failed 1 test of 134.
t/form.t ............... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/134 subtests 

Test Summary Report
-------------------
t/form.t             (Wstat: 256 (exited 1) Tests: 134 Failed: 1)
  Failed test:  15
  Non-zero exit status: 1
Files=12, Tests=223,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.50 cusr  0.10 csys =  0.63 CPU)
Result: FAIL
Failed 1/12 test programs. 1/223 subtests failed.
make: *** [test_dynamic] Error 1
```

**Comment by haarg** [comment] 2024-10-16 12:03
Duplicate of #50

**Closed by haarg** 2024-10-16 12:03 UTC
